### ISSUE TITLE
Backend status `ok` but maintenance agents are missing

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#101]
While setting up my cluster, a node was having some problems and I got an exception during `add_albacluster`. But the backend status was `OK`, I noticed some problems after initializing the disks and I could not claim them. Apparently the maintenance agents were missing...

```
2016-08-29 15:33:41 73100 +0200 - cmp05 - 28608/139803656456000 - celery/celery.worker.job - 131 - ERROR - Task alba.add_cluster[9d0876e4-8403-4060-a2bd-0e5a2da1e5aa] raised unexpected: ReadTimeout(ReadTimeoutError('None: None',),)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albacontroller.py", line 309, in add_cluster
    AlbaNodeController.checkup_maintenance_agents()
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 416, in checkup_maintenance_agents
    'actual': _get_node_load(name)['total_load'],
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 394, in _get_node_load
    maint_services = asd_node.client.list_maintenance_services()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 208, in list_maintenance_services
    return self._call(requests.get, 'maintenance')['services']
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 56, in _call
    response = method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: None: None
```

**Comment by wimpers** [comment]
@kinvaris did you get an error in the GUI during the add backend? Were you able remove the backend?

**Comment by khenderick** [comment]
Moved because maintenance process location is something the ```framework-alba-plugin``` handles
