### ISSUE TITLE
Alba disk fails to mount because disk_by_id entry is already present in /etc/fstab

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#163]
We saw this error on a GIG environment. After some digging we found that the `/etc/fstab` entry for that that disk was already present on the node. During mount of the OSD, the asd-manager things that because its already present in `/etc/fstab`, the right mount point is also present.

```
2016-11-22 14:04:11 52100 +0100 - stor-03.cl-g8-uk1 - 40093/139755293910784 - asd-manager/werkzeug - 1180 - INFO - 10.21.2.21 - - [22/Nov/2016 14:04:11] "GET /asds HTTP/1.1" 200 -
mount: can't find /mnt/alba-asd/2ppuIwAsyD3hzTrO in /etc/fstab or /etc/mtab
Traceback (most recent call last):
  File "/opt/asd-manager/source/app/decorators.py", line 73, in new_function
    return_data = f(*args, **kwargs)
  File "/opt/asd-manager/source/app/api.py", line 103, in add_disk
    DiskController.prepare_disk(device_alias=alias)
  File "/opt/asd-manager/source/controllers/disk.py", line 238, in prepare_disk
    check_output('mount {0}'.format(mountpoint), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'mount /mnt/alba-asd/2ppuIwAsyD3hzTrO' returned non-zero exit status 1
```

After removing this entry from `/etc/fstab`, it all worked again:
```
/dev/disk/by-id/ata-ST8000NM0055-1RM112_ZA12VWVB-part1  /mnt/alba-asd/tVrR7qIlqXDl7pv6  xfs  defaults,nofail,noatime,discard  0  2
```

**Steps to reproduce:** Put a non-claimed disk in `/etc/fstab` and try to initialize the disk.

**Comment by wimpers** [comment]
@kinvaris can we in short term tackle this in the Swiper.sh?
