### ISSUE TITLE
Support agent: pyrakoon receives unknown master during master validation

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/alba-asdmanager#182]
Work-around: Restarting the support agent. 

Related to: https://github.com/openvstorage/alba-asdmanager/issues/155

```
Dec  5 15:26:42 stor-07 python2[31509]: 2016-12-05 15:26:42 44000 +0100 - stor-07.be-g8-4 - 31509/140086121719552 - arakoon_client/pyrakoon - 346236 - ERROR - 'CSNQF5zD26A1WfZi' : Message exchange with node CSNQF5zD26A1WfZi failed
Dec  5 15:26:42 stor-07 python2[31509]: Traceback (most recent call last):
Dec  5 15:26:42 stor-07 python2[31509]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1137, in _send_message
Dec  5 15:26:42 stor-07 python2[31509]:     connection = self._get_connection(node_id)
Dec  5 15:26:42 stor-07 python2[31509]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1227, in _get_connection
Dec  5 15:26:42 stor-07 python2[31509]:     node_location = self._config.getNodeLocation(node_id)
Dec  5 15:26:42 stor-07 python2[31509]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1014, in getNodeLocation
Dec  5 15:26:42 stor-07 python2[31509]:     ips, port = self.getNodeLocations(nodeId)
Dec  5 15:26:42 stor-07 python2[31509]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 999, in getNodeLocations
Dec  5 15:26:42 stor-07 python2[31509]:     return self._nodes[nodeId]
Dec  5 15:26:42 stor-07 python2[31509]: KeyError: 'CSNQF5zD26A1WfZi'
```
```
Dec  5 15:26:42 stor-07 python2[31509]: 2016-12-05 15:26:42 44100 +0100 - stor-07.be-g8-4 - 31509/140086121719552 - arakoon_client/pyrakoon - 346237 - ERROR - 'CSNQF5zD26A1WfZi': Unable to validate master on node CSNQF5zD26A1WfZi
Dec  5 15:26:42 stor-07 python2[31509]: Traceback (most recent call last):
Dec  5 15:26:42 stor-07 python2[31509]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1185, in determine_master
Dec  5 15:26:42 stor-07 python2[31509]:     self._validate_master_id(self.master_id):
Dec  5 15:26:42 stor-07 python2[31509]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1216, in _validate_master_id
Dec  5 15:26:42 stor-07 python2[31509]:     other_master_id = self._get_master_id_from_node(master_id)
Dec  5 15:26:42 stor-07 python2[31509]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1207, in _get_master_id_from_node
Dec  5 15:26:42 stor-07 python2[31509]:     connection = self._send_message(node_id, data)
Dec  5 15:26:42 stor-07 python2[31509]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1146, in _send_message
Dec  5 15:26:42 stor-07 python2[31509]:     self._connections.pop(node_id).close()
Dec  5 15:26:42 stor-07 python2[31509]: KeyError: 'CSNQF5zD26A1WfZi'
```

**Comment by wimpers** [comment]
Related to https://github.com/openvstorage/alba-asdmanager/issues/155 ?

**Comment by khenderick** [comment]
It is indeed the same issue, but another service, and needs a slightly different approach to fix. Hence a separate ticket.
