### ISSUE TITLE
Update of openvstorage-sdm package fails on storage nodes due to missing at dependency

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/alba-asdmanager#190]
Log entries:

node running update process:
```
2016-12-13 09:23:55 90300 +0100 - ctrl-roub-01 - 129759/140455993808640 - update/alba-plugin - 84 - DEBUG - 172.20.20.142: Updating SDM package openvstorage-sdm (1.6.5-fargo.1-1 --> 1.6.7-fargo.1-1)
2016-12-13 09:25:59 50800 +0100 - ctrl-roub-01 - 129759/140455993808640 - update/core - 85 - ERROR - 172.20.20.1: Package installation hook package_install_sdm failed with error: Failed to update SDM
Traceback (most recent call last):
  File "ovs/lib/update.py", line 554, in execute_update
    function(package_info=packages_to_update)
  File "ovs/lib/helpers/..//albaupdate.py", line 353, in package_install_sdm
    alba_node.client.execute_update(pkg_name)
  File "ovs/extensions/plugins/asdmanager.py", line 248, in execute_update
    raise Exception('Failed to update SDM')
Exception: Failed to update SDM
```

Node on which actual update is executed show only polling in this timeframe:
```
Dec 13 09:24:49 cap-grav-05 python[15437]: 2016-12-13 09:24:49 56600 +0100 - cap-grav-05 - 15437/140601056032512 - asd-manager/update - 295022 - INFO - Installed version for package openvstorage-sdm: 1.6.5-fargo.1-1
Dec 13 09:24:49 cap-grav-05 python[15437]: 2016-12-13 09:24:49 56600 +0100 - cap-grav-05 - 15437/140601056032512 - asd-manager/update - 295023 - INFO - Candidate version for package openvstorage-sdm: 1.6.7-fargo.1-1
Dec 13 09:24:49 cap-grav-05 python[15437]: 2016-12-13 09:24:49 56700 +0100 - cap-grav-05 - 15437/140601056032512 - asd-manager/werkzeug - 295024 - INFO - 172.20.20.103 - - [13/Dec/2016 09:24:49] "POST /update/execute/running HTTP/1.1" 200 -
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/alba-asdmanager/pull/192 --> openvstorage-sdm-1.6.8-rev.495.135932c

**Comment by pploegaert** [comment]
VALIDATION OK
