### ISSUE TITLE
1 broken disk makes every disk broken in the GUI

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#91]
This was observed in a test environment:

1 disk was indeed broken but in the GUI everything was broken:

```
2016-05-18 17:06:24.787940 - Listing disks
Traceback (most recent call last):
  File "/opt/asd-manager/source/app/decorators.py", line 71, in new_function
    return_data = f(*args, **kwargs)
  File "/opt/asd-manager/source/app/api.py", line 72, in list_disks
    return DiskController.list_disks()
  File "/opt/asd-manager/source/controllers/disk.py", line 95, in list_disks
    disks[device].update({'state': 'error',
KeyError: 'scsi-2001b4d2a80e9a850'
```

Related to OVS-4550

**Comment by khenderick** [comment]
Technically, the above reported error wasn't valid anymore, but I discovered and resolved another error in the same path.

**Comment by khenderick** [comment]
Forgot the verification step

**Comment by deepshirsath** [comment]
PASSED on - _**Open vStorage: 2.7.1-fargo.2-1**_

- setup single node env with one faulty disk installed. (SDA=Faulty disk)

![smartclt-sda](https://cloud.githubusercontent.com/assets/14201912/17587375/9a527b4c-5fe5-11e6-9b9f-b59787d116db.PNG)


- Failed disk (SDA) could not be initialzed due to Input/output error as seen in 'asd-manager.log'

- asd-manager.log



> 2016-08-11

 16:43:52 43600 +0530 - ubuntuovskvm - 20195/140385212385024 - asd-manager/api - 1467 - INFO - Listing disks
2016-08-11 16:43:52 47400 +0530 - ubuntuovskvm - 20195/140385212385024 - asd-manager/werkzeug - 1468 - INFO - 192.168.16.112 - - [11/Aug/2016 16:43:52] "GET /disks HTTP/1.1" 200 -
2016-08-11 16:43:52 53300 +0530 - ubuntuovskvm - 20195/140385212385024 - asd-manager/werkzeug - 1469 - INFO - 192.168.16.112 - - [11/Aug/2016 16:43:52] "GET /asds HTTP/1.1" 200 -
mkfs.xfs: libxfs_device_zero write failed: Input/output error
Traceback (most recent call last):
  File "/opt/asd-manager/source/app/decorators.py", line 73, in new_function
    return_data = f(*args, **kwargs)
  File "/opt/asd-manager/source/app/api.py", line 103, in add_disk
    DiskController.prepare_disk(disk_id)
  File "/opt/asd-manager/source/controllers/disk.py", line 158, in prepare_disk
    check_output('mkfs.xfs -qf {0}-part1'.format(disk_by_id), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'mkfs.xfs -qf /dev/disk/by-id/ata-ST31000524AS_9VPC0ZD2-part1' returned non-zero exit status 1
2016-08-11 16:43:56.843866 - None
2016-08-11 16:43:56 84500 +0530 - ubuntuovskvm - 20195/140385221302016 - asd-manager/werkzeug - 1470 - INFO - 192.168.16.112 - - [11/Aug/2016 16:43:56] "POST /disks/ata-ST31000524AS_9VPC0ZD2/add HTTP/1.1" 500 

> -



- Other SATA/SSD disks does not show broken on OVS gui.

![asds](https://cloud.githubusercontent.com/assets/14201912/17587468/3e6a95ca-5fe6-11e6-8c88-47f8003d116f.PNG)
